import './globals.css'


export const metadata = {
  title: 'Food court',
  description: 'Generated by Masha Christopher',
}

export default function RootLayout({ children }) {
  // for data fetching 
  // import useSWR from 'swr'
  // const { data, error } = useSWR('/api/navigation', fetcher)
  // if(error) 
  //   return
  //     <div>
  //       Failed to load
  //     </div>
  // if(!data)
  //   return
  //     <div>
  //       Loading...
  //     </div> 
  return (
    <html lang="en">
      {/* <link rel="preconnect" href="https://fonts.googleapis.com"/> */}
    {/* <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/> */}
    <link href="https://fonts.googleapis.com/css2?family=Varela+Round&display=swap" rel="stylesheet"/>
      <body>
        {children}
      </body>
    </html>
  )
}
