// import Button from '../Button'
import '../globals.css'
import Nav from './Nav'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">        
      <body>
        {/* <div className='h-screen w-[100%] relative'> */}
        <Nav/>
        {children}
        {/* </div> */}
      </body>
    </html>
  )
}
